# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def ad_pods
  # As we are using AppHarbr we should be careful when updating max adapters
  # Check this link for adapters updates https://helpcenter.appharbr.com/hc/en-us/articles/17047099021329-Before-Starting
  pod 'AppLovinSDK', '12.5.0'
  pod 'AppLovinMediationGoogleAdapter'
  pod 'AppLovinMediationGoogleAdManagerAdapter', '11.5.0'
  pod 'AppLovinMediationAmazonAdMarketplaceAdapter'
  pod 'AppLovinMediationBidMachineAdapter', '2.7.0'
  pod 'AppLovinMediationInMobiAdapter', '10.7.2'
  pod 'AppLovinMediationVungleAdapter', '7.2.1'
  pod 'AppLovinMediationLineAdapter'
  pod 'AppLovinMediationFacebookAdapter', '6.15.0'
  pod 'AppLovinMediationMintegralAdapter', '7.6.6'
  pod 'AppLovinMediationByteDanceAdapter', '5.9.0.7'
  pod 'bigo-ads-max-adapter', "4.2.3"
  pod 'AppHarbrSDK'
  pod 'AmazonPublisherServicesSDK'
end

def consent_pods
  pod 'ConsentViewController'
end


target 'voodoo-gdpr-sp-sample-ios' do
  ad_pods
  consent_pods
  pod 'Kingfisher'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
            config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = "YES"
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
            config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
    end
end
