# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def ad_pods
  pod 'AppLovinSDK', '12.5.0'
  pod 'AppLovinMediationGoogleAdapter'
  pod 'AppLovinMediationGoogleAdManagerAdapter'
  pod 'AppHarbrSDK'
  pod 'AmazonPublisherServicesSDK'
  pod 'AppLovinMediationAmazonAdMarketplaceAdapter'
  pod 'AppLovinMediationBidMachineAdapter', '2.6.1.0'
  pod 'AppLovinMediationChartboostAdapter'
  pod 'AppLovinMediationFyberAdapter'
  pod 'AppLovinMediationInMobiAdapter', '10.7.1'
  pod 'AppLovinMediationIronSourceAdapter'
  pod 'AppLovinMediationVungleAdapter'
  pod 'AppLovinMediationLineAdapter'
  pod 'AppLovinMediationFacebookAdapter'
  pod 'AppLovinMediationMintegralAdapter'
  pod 'AppLovinMediationOguryPresageAdapter'
  pod 'AppLovinMediationByteDanceAdapter'
  pod 'AppLovinMediationUnityAdsAdapter'
  pod 'bigo-ads-max-adapter', "4.2.0"
  pod 'AppLovinMediationMobileFuseAdapter'
end

target 'voodoo-gdpr-sp-sample-ios' do
  ad_pods
  
  pod 'SnapKit'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
            config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = "YES"
            config.build_settings['CODE_SIGN_IDENTITY'] = ''
            config.build_settings['ENABLE_BITCODE'] = 'NO'
          config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
    end
end
